name: Tests and publish workflow

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason of the publishment'
        required: true
        default: 'New version'

jobs:
  tests-and-publish:
    runs-on: ubuntu-22.04
    environment: Production

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Configure npm registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install Dependencies and test
        run: |
          pnpm install
          pnpm test
      - name: Publish on npm
        if: matrix.node-version == '20.x'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --no-git-checks
