name: Tests and publish workflow

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'Version to bump'
        required: true
        default: 'patch'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    environment: Production
    steps:
      - name: Setup environment
        uses: ./.github/workflows/setup-environment.yml
      - name: Run tests
        run: pnpm test

  publish:
    needs: ['test']
    runs-on: ubuntu-22.04
    environment: Production
    steps:
      - name: Setup environment
        uses: ./.github/workflows/setup-environment.yml
      # - name: 'Automated Version Bump'
      #   uses: 'phips28/gh-action-bump-version@master'
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     version-type: ${{ inputs.version-bump }}
      # - name: Publish on npm
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: pnpm publish --access public --no-git-checks
