name: Tests workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason of the trigger'
        required: true
        default: 'General purpose'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Detect Trigger Reason
        run: echo "Triggered because of ${{ github.event_name }} for ${{ inputs.reason }}"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies and test
        run: |
          pnpm install
          pnpm test
